import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const bwSeidoRound = localFont({
  src: [
    {
      path: "../public/fonts/BwSeidoRoundDEMO-Thin.woff2",
      weight: "100",
      style: "normal",
    },
    {
      path: "../public/fonts/BwSeidoRoundDEMO-Light.woff2",
      weight: "300",
      style: "normal",
    },
    {
      path: "../public/fonts/BwSeidoRoundDEMO-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/BwSeidoRoundDEMO-Medium.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "../public/fonts/BwSeidoRoundDEMO-Bold.woff2",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-bw-seido-round",
  display: "swap",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "SMGH",
  description: "Generated by SMGH",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={bwSeidoRound.variable}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
      >
        <main className="flex-1">{children}</main>
      </body>
    </html>
  );
}
